redirect404_home.settings:
  type: config_object
  label: 'Redirect 404 to Home Page'
  mapping:
    redirection:
      type: select
      label: 'Redirection type'
    status_message:
      type: text
      label: 'Status message text'
