stages:
  - build
  - deploy

variables:
  GIT_STRATEGY: clone
  CONTAINER_IMAGE: harbor.dev.kubix.tm.com.my/tmw-web/tmw:ba2222c
  CONTAINER_IMAGE_PROD: harbor.prod.kubix.tm.com.my/tmw-web/tmw:ba2222c
  HARBOR_PASSWORD : QE7vRX7LktiNgzE2u3BNUap8eek7j94d

build:
  stage: build
  script:
    - docker login harbor.dev.kubix.tm.com.my -u 'robot$tmw-web+tmw-web' -p ${HARBOR_PASSWORD}
    - docker build -t ${CONTAINER_IMAGE} .
    - docker tag ${CONTAINER_IMAGE} ${CONTAINER_IMAGE}
    - docker push ${CONTAINER_IMAGE}
  tags:
    - kubix-runner


deploy-dev:
  stage: deploy
  script:
    - kubectl config set-cluster k8s --server="${K8_IP}"
    - kubectl config set clusters.k8s.certificate-authority-data ${K8_CA}
    - kubectl config set-credentials gitlab --token="${K8_TOKEN}"
    - kubectl config set-context default --cluster=k8s --user=gitlab
    - kubectl config use-context default
    - kubectl config set-context --current --namespace="${K8_NS}"
    - kubectl get all
    - cat k8s/drupal-deployment.yml | sed -i "s/<VERSION>/${CI_COMMIT_SHORT_SHA}/g" | kubectl apply -f -
    - kubectl apply -f k8s/drupal_ingress.yml
  environment:
    name: development
  tags:
    - kubix-runner
  only:
    - tmgdev
  # when: manual
