<?php

/**
 * @file
 * Contains inline_formatter_field.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function inline_formatter_field_help($route_name, RouteMatchInterface $route_match) {
  $output = '';
  switch ($route_name) {
    // Help for the inline formatter field module.
    case 'help.page.inline_formatter_field':
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The Inline Formatter Field module allows for templating and styling of entities on the front side. This module will create a new field type called "Inline Formatter" which is a boolean. When the boolean is checked the field will render what is entered in the "HTML or Twig Format" field for the formatter\'s settings in the "Manage Display" screen of the entity. This module makes use of the ACE Editor javascript library for ease of editing.') . '</p>';
      $output .= '<p>' . t('In order to use the field, add the field as you would any other field. In the manage display form, the settings form for the field will have a text area in which any HTML or Twig can be entered. The field will appear as a checkbox on the content form, and the HTML or Twig will render if the field is checked.') . '</p>';
      $output .= '<p>' . t('In order to edit the HTML or Twig in the field, a user must have a role with permission to edit inline formmater field formats. Themes and other settings for the editor can be adjusted in the inline formatter field settings form by users with roles that have permission to edit inline formmater field settings.') . '</p>';
      break;
  }
  return $output;
}

/**
 * Implements hook_library_info_alter().
 */
function inline_formatter_field_library_info_alter(&$libraries, $extension) {
  if (isset($libraries['inline_formatter_display'])) {
    $settings = \Drupal::config('inline_formatter_field.settings');
    $ace = $settings->get('ace_source');
    $fa = $settings->get('fa_source');

    $libraries['inline_formatter_display']['js'][$ace] = [
      'type' => substr($ace, 0, 7) === 'http://' || substr($ace, 0, 8) === 'https://' ? 'external' : 'file',
      'minified' => substr($ace, -7) === '.min.js' ? TRUE : FALSE,
    ];
    $libraries['inline_formatter_display']['css']['theme'][$fa] = [
      'type' => substr($fa, 0, 7) === 'http://' || substr($fa, 0, 8) === 'https://' ? 'external' : 'file',
      'minified' => substr($fa, -8) === '.min.css' ? TRUE : FALSE,
    ];
  }
}
