_core:
  default_config_hash: UVH1aJ4b44UM-VdPVN7hNNuuVqfReJxwfVeDQH1Hvsk
ignored_config_entities:
  - '*site_specific__*'
  - 'block.block.*'
  - 'webform.webform.*'
  - 'google_tag.container.*'
  - core.entity_view_display.user.user.default
  - system.site
  - swiftmailer.transport
  - system.performance
  - automated_cron.settings
  - captcha.settings
  - tmg_utility.web_pull_settings
