_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  tmg_utility: -5
  admin_toolbar: 0
  automated_cron: 0
  better_exposed_filters: 0
  big_pipe: 0
  block: 0
  block_content: 0
  block_visibility_groups: 0
  bootstrap4_modal: 0
  breakpoint: 0
  captcha: 0
  ckeditor: 0
  clientside_validation: 0
  clientside_validation_jquery: 0
  color: 0
  comment: 0
  config: 0
  config_ignore: 0
  contact: 0
  contextual: 0
  csv_serialization: 0
  ctools: 0
  datetime: 0
  dblog: 0
  devel: 0
  devel_kint_extras: 0
  disable_messages: 0
  dynamic_page_cache: 0
  editor: 0
  email_registration: 0
  encrypt: 0
  entity_redirect: 0
  entity_reference_revisions: 0
  entity_submit_redirect: 0
  entityform_block: 0
  feeds: 0
  feeds_tamper: 0
  field: 0
  field_permissions: 0
  field_ui: 0
  field_validation: 0
  file: 0
  filter: 0
  form_mode_control: 0
  help: 0
  history: 0
  ief_table_view_mode: 0
  image: 0
  inline_entity_form: 0
  inline_form_errors: 0
  inline_formatter_display: 0
  inline_formatter_field: 0
  jquery_ui: 0
  jquery_ui_datepicker: 0
  jquery_ui_slider: 0
  jquery_ui_touch_punch: 0
  key: 0
  layout_builder: 0
  layout_builder_modal: 0
  layout_discovery: 0
  link: 0
  link_target: 0
  login_destination: 0
  mailsystem: 0
  media: 0
  media_library: 0
  menu_export: 0
  menu_link_attributes: 0
  menu_link_content: 0
  menu_per_role: 0
  menu_ui: 0
  node: 0
  nodeaccess: 0
  options: 0
  page_cache: 0
  password_eye: 0
  password_policy_characters: 0
  password_policy_length: 0
  path: 0
  path_alias: 0
  r4032login: 0
  rdf: 0
  real_aes: 0
  recaptcha: 0
  redirect: 0
  redirect404_home: 0
  rest: 0
  search: 0
  serialization: 0
  shortcut: 0
  swiftmailer: 0
  system: 0
  tamper: 0
  taxonomy: 0
  telephone: 0
  telephone_validation: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  user: 0
  views_autocomplete_filters: 0
  views_bulk_operations: 0
  views_data_export: 0
  views_entity_form_field: 0
  views_remote_data: 0
  views_ui: 0
  we_megamenu: 0
  webform: 0
  webform_ui: 0
  webform_views: 0
  password_policy: 10
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  bartik: 0
  seven: 0
  tmwone: 0
  stable: 0
  classy: 0
  bootstrap: 0
  tmw_theme: 0
profile: standard
