_core:
  default_config_hash: CXhei_vpaZk-3f_Mj2cH0YmpK-ZpKHoSzVA3yZrDq0g
definitions:
  contact__site_page:
    weight: -50
    menu_name: footer
    parent: ''
    enabled: false
    expanded: false
  system__admin_content:
    weight: -81
    menu_name: admin
    parent: system.admin
    expanded: false
    enabled: true
  system__admin_structure:
    weight: -80
    menu_name: admin
    parent: system.admin
    expanded: false
    enabled: true
  system__themes_page:
    weight: -79
    menu_name: admin
    parent: system.admin
    expanded: false
    enabled: true
  system__modules_list:
    weight: -78
    menu_name: admin
    parent: system.admin
    expanded: false
    enabled: true
  system__admin_config:
    weight: -77
    menu_name: admin
    parent: system.admin
    expanded: false
    enabled: true
  entity__user__collection:
    weight: -76
    menu_name: admin
    parent: system.admin
    expanded: false
    enabled: true
  system__admin_reports:
    weight: -75
    menu_name: admin
    parent: system.admin
    expanded: false
    enabled: true
  help__main:
    weight: -74
    menu_name: admin
    parent: system.admin
    expanded: false
    enabled: true
