209:
  id:
    value: '209'
  uuid:
    value: f65e8114-68a9-4fa7-820c-b2aa145d8d3f
  revision_id:
    value: '209'
  langcode:
    value: en
  bundle:
    value: menu_link_content
  revision_created:
    value: '1647924812'
  revision_user: false
  revision_log_message: false
  enabled:
    value: '1'
  title:
    value: Dashboards
  description: false
  menu_name:
    value: after-login
  link:
    uri: 'internal:/dashboard'
    title: ''
    options:
      attributes:
        class:
          - icon-dashboard
  external:
    value: '0'
  rediscover:
    value: '1'
  weight:
    value: '-50'
  expanded:
    value: '0'
  parent: false
  changed:
    value: '1648104197'
  default_langcode:
    value: '1'
  revision_default:
    value: '1'
  revision_translation_affected:
    value: '1'
211:
  id:
    value: '211'
  uuid:
    value: 4c5b3f6b-3ddc-41b6-bdec-e5bdbe30d3e8
  revision_id:
    value: '211'
  langcode:
    value: en
  bundle:
    value: menu_link_content
  revision_created:
    value: '1647924861'
  revision_user: false
  revision_log_message: false
  enabled:
    value: '1'
  title:
    value: 'Enquiry Form'
  description: false
  menu_name:
    value: after-login
  link:
    uri: 'internal:/enquiry-form'
    title: ''
    options:
      attributes:
        class:
          - icon-enquiry-form
  external:
    value: '0'
  rediscover:
    value: '1'
  weight:
    value: '-49'
  expanded:
    value: '1'
  parent: false
  changed:
    value: '1648104281'
  default_langcode:
    value: '1'
  revision_default:
    value: '1'
  revision_translation_affected:
    value: '1'
213:
  id:
    value: '213'
  uuid:
    value: 6baf741a-c292-4d2a-8b82-a704c18f8cf0
  revision_id:
    value: '213'
  langcode:
    value: en
  bundle:
    value: menu_link_content
  revision_created:
    value: '1647924903'
  revision_user: false
  revision_log_message: false
  enabled:
    value: '1'
  title:
    value: 'Price Calculator(PH2)'
  description: false
  menu_name:
    value: after-login
  link:
    uri: 'internal:/'
    title: ''
    options: {  }
  external:
    value: '0'
  rediscover:
    value: '1'
  weight:
    value: '-48'
  expanded:
    value: '1'
  parent:
    value: 'menu_link_content:4c5b3f6b-3ddc-41b6-bdec-e5bdbe30d3e8'
  changed:
    value: '1647925073'
  default_langcode:
    value: '1'
  revision_default:
    value: '1'
  revision_translation_affected:
    value: '1'
217:
  id:
    value: '217'
  uuid:
    value: 13565bc3-b66e-4249-9a8a-e3cc7c71a16b
  revision_id:
    value: '217'
  langcode:
    value: en
  bundle:
    value: menu_link_content
  revision_created:
    value: '1647924912'
  revision_user: false
  revision_log_message: false
  enabled:
    value: '1'
  title:
    value: 'Get Quotes'
  description: false
  menu_name:
    value: after-login
  link:
    uri: 'internal:/enquiry-form'
    title: ''
    options:
      attributes:
        class: {  }
  external:
    value: '0'
  rediscover:
    value: '1'
  weight:
    value: '-50'
  expanded:
    value: '1'
  parent:
    value: 'menu_link_content:4c5b3f6b-3ddc-41b6-bdec-e5bdbe30d3e8'
  changed:
    value: '1648104293'
  default_langcode:
    value: '1'
  revision_default:
    value: '1'
  revision_translation_affected:
    value: '1'
232:
  id:
    value: '232'
  uuid:
    value: 42c2320d-a894-41d7-b73a-6642195279d2
  revision_id:
    value: '232'
  langcode:
    value: en
  bundle:
    value: menu_link_content
  revision_created:
    value: '1647924941'
  revision_user: false
  revision_log_message: false
  enabled:
    value: '1'
  title:
    value: 'Product Enquery'
  description: false
  menu_name:
    value: after-login
  link:
    uri: 'internal:/'
    title: ''
    options: {  }
  external:
    value: '0'
  rediscover:
    value: '1'
  weight:
    value: '-49'
  expanded:
    value: '1'
  parent:
    value: 'menu_link_content:4c5b3f6b-3ddc-41b6-bdec-e5bdbe30d3e8'
  changed:
    value: '1647925073'
  default_langcode:
    value: '1'
  revision_default:
    value: '1'
  revision_translation_affected:
    value: '1'
254:
  id:
    value: '254'
  uuid:
    value: e4c59a92-a9d4-44df-a5dc-9f176117edb4
  revision_id:
    value: '254'
  langcode:
    value: en
  bundle:
    value: menu_link_content
  revision_created:
    value: '1647945494'
  revision_user: false
  revision_log_message: false
  enabled:
    value: '1'
  title:
    value: 'Self Service Coverage'
  description: false
  menu_name:
    value: after-login
  link:
    uri: 'internal:/'
    title: ''
    options:
      attributes:
        class:
          - icon-self-service-coverage
  external:
    value: '0'
  rediscover:
    value: '1'
  weight:
    value: '-48'
  expanded:
    value: '0'
  parent: false
  changed:
    value: '1648015471'
  default_langcode:
    value: '1'
  revision_default:
    value: '1'
  revision_translation_affected:
    value: '1'
264:
  id:
    value: '264'
  uuid:
    value: b793b6d2-8959-473c-b333-9c684cc2f3e6
  revision_id:
    value: '264'
  langcode:
    value: en
  bundle:
    value: menu_link_content
  revision_created:
    value: '1647945569'
  revision_user: false
  revision_log_message: false
  enabled:
    value: '1'
  title:
    value: Support
  description: false
  menu_name:
    value: after-login
  link:
    uri: 'internal:/'
    title: ''
    options:
      attributes:
        class:
          - icon-support
  external:
    value: '0'
  rediscover:
    value: '1'
  weight:
    value: '-47'
  expanded:
    value: '0'
  parent: false
  changed:
    value: '1648015491'
  default_langcode:
    value: '1'
  revision_default:
    value: '1'
  revision_translation_affected:
    value: '1'
274:
  id:
    value: '274'
  uuid:
    value: fa2b02d6-841a-403c-82ef-5110c95a7667
  revision_id:
    value: '274'
  langcode:
    value: en
  bundle:
    value: menu_link_content
  revision_created:
    value: '1647945636'
  revision_user: false
  revision_log_message: false
  enabled:
    value: '1'
  title:
    value: Resources
  description: false
  menu_name:
    value: after-login
  link:
    uri: 'internal:/'
    title: ''
    options:
      attributes:
        class:
          - icon-resources
  external:
    value: '0'
  rediscover:
    value: '1'
  weight:
    value: '-46'
  expanded:
    value: '1'
  parent: false
  changed:
    value: '1648015514'
  default_langcode:
    value: '1'
  revision_default:
    value: '1'
  revision_translation_affected:
    value: '1'
322:
  id:
    value: '322'
  uuid:
    value: 1b05e282-867c-4403-92b4-9e23f46e2106
  revision_id:
    value: '322'
  langcode:
    value: en
  bundle:
    value: menu_link_content
  revision_created:
    value: '1647945692'
  revision_user: false
  revision_log_message: false
  enabled:
    value: '1'
  title:
    value: Announcement
  description: false
  menu_name:
    value: after-login
  link:
    uri: 'internal:/'
    title: ''
    options: {  }
  external:
    value: '0'
  rediscover:
    value: '1'
  weight:
    value: '-50'
  expanded:
    value: '0'
  parent:
    value: 'menu_link_content:fa2b02d6-841a-403c-82ef-5110c95a7667'
  changed:
    value: '1647945792'
  default_langcode:
    value: '1'
  revision_default:
    value: '1'
  revision_translation_affected:
    value: '1'
227:
  id:
    value: '227'
  uuid:
    value: 6ffbfc4c-aa29-40e4-954b-eaaf0da464c9
  revision_id:
    value: '227'
  langcode:
    value: en
  bundle:
    value: menu_link_content
  revision_created:
    value: '1647945715'
  revision_user: false
  revision_log_message: false
  enabled:
    value: '1'
  title:
    value: Promotion
  description: false
  menu_name:
    value: after-login
  link:
    uri: 'internal:/'
    title: ''
    options: {  }
  external:
    value: '0'
  rediscover:
    value: '1'
  weight:
    value: '-49'
  expanded:
    value: '0'
  parent:
    value: 'menu_link_content:fa2b02d6-841a-403c-82ef-5110c95a7667'
  changed:
    value: '1647945792'
  default_langcode:
    value: '1'
  revision_default:
    value: '1'
  revision_translation_affected:
    value: '1'
225:
  id:
    value: '225'
  uuid:
    value: 5523bf72-ec3b-4c12-b634-cacd39771c93
  revision_id:
    value: '225'
  langcode:
    value: en
  bundle:
    value: menu_link_content
  revision_created:
    value: '1647945783'
  revision_user: false
  revision_log_message: false
  enabled:
    value: '1'
  title:
    value: 'Marketing Materials'
  description: false
  menu_name:
    value: after-login
  link:
    uri: 'internal:/'
    title: ''
    options: {  }
  external:
    value: '0'
  rediscover:
    value: '1'
  weight:
    value: '-48'
  expanded:
    value: '0'
  parent:
    value: 'menu_link_content:fa2b02d6-841a-403c-82ef-5110c95a7667'
  changed:
    value: '1647945792'
  default_langcode:
    value: '1'
  revision_default:
    value: '1'
  revision_translation_affected:
    value: '1'
222:
  id:
    value: '222'
  uuid:
    value: fbe94141-35b9-4115-bbd6-b60d59284628
  revision_id:
    value: '222'
  langcode:
    value: en
  bundle:
    value: menu_link_content
  revision_created:
    value: '1648112274'
  revision_user: false
  revision_log_message: false
  enabled:
    value: '1'
  title:
    value: 'Link 1'
  description: false
  menu_name:
    value: after-login
  link:
    uri: 'internal:/'
    title: ''
    options:
      attributes:
        class: {  }
  external:
    value: '0'
  rediscover:
    value: '1'
  weight:
    value: '0'
  expanded:
    value: '0'
  parent:
    value: 'menu_link_content:4c5b3f6b-3ddc-41b6-bdec-e5bdbe30d3e8'
  changed:
    value: '1648112274'
  default_langcode:
    value: '1'
  revision_default:
    value: '1'
  revision_translation_affected:
    value: '1'
