_core:
  default_config_hash: qVQ1RHKobjP6sdrM7AyswE45vzpPM9ff9JGcyTdOFAQ
otp_no_of_digits: '6'
otp_otp_mail_subject: 'Your Requested One Time Password'
otp_otp_mail_body: "Dear [user:name],\r\n\r\nYour One Time Password for completing your transaction Drupal OTP Verification is: [user:otp]\r\n\r\nPlease use this Password to complete your transaction. Do not share this Password with anyone.\r\n\r\nThank you,\r\n[site:name] team"
user_otp_generate_threshold: '4'
user_otp_generate_time_window: '3'
user_otp_submit_threshold: '15'
user_otp_submit_time_window: '1'
