_core:
  default_config_hash: Wkmn-jEru9OubwF4XTXJNzX89A62mX8PlyDco6TMYl4
smtp_host: smtp.gmail.com
smtp_hostbackup: ''
smtp_port: 465
smtp_protocol: ssl
smtp_username: lodh.arghajit@gmail.com
smtp_password: Poiqwe@123
smtp_hide_password: true
smtp_fromname: TMG
smtp_always_replyto: false
smtp_keepalive: false
smtp_debug: 4
smtp_debug_log: true
phpmailer_smtp_test: ''
smtp_ssl_verify_peer: true
smtp_ssl_verify_peer_name: false
smtp_ssl_allow_self_signed: true
smtp_envelope_sender_option: default
smtp_envelope_sender: ''
smtp_ehlo_host: ''
smtp_timeout: 30
