node.type.*.third_party.entity_redirect: &settings
  type: mapping
  label: 'Entity Redirect per entity settings'
  mapping:
    redirect:
      type: mapping
      mapping:
        anonymous:
          type: mapping
          mapping: &base
            active:
              type: boolean
              label: 'Whether this type of redirect is active or not.'
            destination:
              type: string
              label: 'The redirect type.'
            url:
              type: string
              label: 'The url to redirect to if a local url.'
            external:
              type: string
              label: 'An external redirect location.'
        add:
          type: mapping
          mapping: &full
            <<: *base
            personalizable:
              type: boolean
              label: 'Whether privileged users can customize this for themselves.'
        edit:
          type: mapping
          mapping:
            <<: *full
        delete:
          type: mapping
          mapping:
            <<: *full

media.type.*.third_party.entity_redirect:
  <<: *settings

taxonomy.vocabulary.*.third_party.entity_redirect:
  <<: *settings
