disable_messages.settings:
  type: mapping
  label: Settings
  mapping:
    disable_messages_enable:
      type: string
    disable_messages_exclude_users:
      type: string
    disable_messages_filter_by_page:
      type: integer
    disable_messages_page_filter_paths:
      type: string
    disable_messages_enable_debug:
      type: string
    disable_messages_debug_visible_div:
      type: string
    disable_messages_ignore_patterns:
      type: string
    disable_messages_ignore_case:
      type: string
